### ISSUE TITLE
Null OptionalInt deseralized as null

### ISSUE THREAD

**Issue by moghaddam** [eclipse/yasson#6]
Null values for optional properties (e.g. Optional, OptionalInt, OptionalLong, OptionalDouble) as mentioned on chapter 3.14.1, should be deserialized as corresponding "empty" value (e.g. OptionalInt.empty(), etc.) but they're getting deserialized as Null values.

**Comment by m0mus** [comment]
Original issue on Yasson forum: https://www.eclipse.org/forums/index.php/t/1083307/

**Comment by m0mus** [comment]
@moghaddam, if you don't mind, I assigned it to you. :)

**Comment by moghaddam** [comment]
I was just checking this issue and I found a solution which solves the problem when the property is an  Optional type. But I just noticed that it doesn't work when it's a generic type. I actually tried to add a new property to PropertyModel class (named optional of boolean type) and then on the PropertyModel constructor, added following initialization:

        this.optional = (propertyType == Optional.class || propertyType == OptionalInt.class ||
                         propertyType == OptionalLong.class || propertyType == OptionalDouble.class);

The problem is, when the property is of generic type, the value of "propertyType" is something like "T" so it doesn't work. I'm looking to find a proper way to access runtime type data there. Do you have any idea? ;)

**Comment by m0mus** [comment]
@bravehorsie is owning this code. Roman, can you help here?

**Comment by bravehorsie** [comment]
Resolving TypeVariables happens during de/serialization runtime, they cannot be resolved when PropertyModel is created. 

Consider:
`class Wrapper<T> {
  public T t;
}`
now you can't say what type T is, because:

`Jsonb runtime = JsonBuilder.create();`

`Wrapper<String> result = jsonb.fromJson(stringValJson, new Wrapper<String>(){}.getGenericSuperClass());` //<- PropertyModel for Wrapper<T> is initialized here

`Wrapper<Integer> result = jsonb.fromJson(integerValJson, new Wrapper<Integer>(){}.getGenericSuperClass());` //<- and reused here

**Comment by bravehorsie** [comment]
Fixed impl, added tests for null deserialization into:
optionals in generic typevars, arrays and collections of optionals.
