### ISSUE TITLE
Unable to obtain Instant from TemporalAccessor: {},ISO,UTC resolved to 2018-01-19 of type java.time.format.Parsed

### ISSUE THREAD

**Issue by afrunt** [eclipse/yasson#83]
Error parsing java.util.Date with custom format. As shown in official guide

<img width="1036" alt="screen shot 2018-01-21 at 6 49 45 pm" src="https://user-images.githubusercontent.com/5786736/35196547-2ece6a56-fedc-11e7-9328-ede1e3e1a788.png">

Steps to reproduce
1. clone maven project from here https://github.com/afrunt/junk/tree/master/yasson-bug
2. run mvn clean package and review the output

Environment
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T10:58:13+03:00)
Maven home: /Users/andrii.frunt/.sdkman/candidates/maven/current
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Users/andrii.frunt/.sdkman/candidates/java/8u151-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.2", arch: "x86_64", family: "mac"

**Comment by bravehorsie** [comment]
This happens because Yasson is using java.time.format.DateTimeFormatter for handling java.util.Date and java.util.Calendar, which is declared by spec. (See javadoc of `@JsonbDateFormat` and spec document section 3.5).

Java 8 time API declares in  design notes:
The API has been designed to reject null early and to be clear about this behavior.

It is unlucky we have such an example in the official guide.

I have added an option (in Yasson, not the API), for defaulting hours, minutes and seconds to zero when parsing trimmed time json strings into date objects, which will make the above example work as if it is parsed with java.util.SimpleDateFormat. 

`.withConfig(new JsonbConfig().setProperty(JsonbConfigProperties.ZERO_TIME_DEFAULTING, true))`

In this case objects requiring timezone may either: define timezone in the format pattern, or if not defined than UTC timezone is used.

Please see my pull request.

**Comment by afrunt** [comment]
Thanks! @bravehorsie 
Looks tricky, but it is better, than nothing

**Comment by bravehorsie** [comment]
I am open to any suggestion to make it better.

**Comment by bravehorsie** [comment]
Please note you can still use HH:mm:ss in patterns when ZERO_TIME_DEFAULTING is on, it just defaults to zero when these are not present.

**Comment by m0mus** [comment]
I don't like the suggested property name. Suggesting to rename it to DATE_TIME_DEFAULTS or ZERO_TIME_AUTOFILLING or ZERO_TIME_DEFAULTS but not DEFAULTING, it looks strange for me.

**Comment by bravehorsie** [comment]
DEFAULTING suffix is aligned to method name in  java.time.format.DateTimeFormatterBuilder, which is used in order to avoid rejecting null values by the java.time API. (See https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatterBuilder.html#parseDefaulting-java.time.temporal.TemporalField-long- )

Maybe it can be ZERO_TIME_PARSE_DEFAULTING than.
